tabs:
  main:
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
          -
            handle: content
            field:
              type: markdown
              localizable: true
  sidebar:
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - 'max:200'
                - 'unique_entry_value:{collection},{id},{site}'
          -
            handle: date
            field:
              type: date
              required: true
              default: now
title: Service
